// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/cache": {
            "delete": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Deletes all cache keys matching cache:*, or a subset matching cache:{prefix}* if the prefix query parameter is provided. Does not affect API key or rate limit data.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Clear Redis cache",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Key prefix filter (e.g. rxnorm, drugnames)",
                        "name": "prefix",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.cacheClearResult"
                        }
                    },
                    "502": {
                        "description": "Redis unavailable",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/keys": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Returns all provisioned API keys with metadata.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "List all API keys",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_finish06_drug-gate_internal_apikey.APIKey"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Provisions a new publishable API key with app name, allowed origins, and rate limit.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Create API key",
                "parameters": [
                    {
                        "description": "Key creation parameters",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.createKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_apikey.APIKey"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/keys/{key}": {
            "get": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Returns metadata for a specific API key.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Get API key details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key (e.g. pk_abc123)",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_apikey.APIKey"
                        }
                    },
                    "404": {
                        "description": "Key not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Marks an API key as inactive. The key remains retrievable but will be rejected by auth middleware.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Deactivate API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key to deactivate",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status: deactivated",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/keys/{key}/rotate": {
            "post": {
                "security": [
                    {
                        "AdminAuth": []
                    }
                ],
                "description": "Creates a new key with the same metadata and sets a grace period expiration on the old key. Both keys are valid during the grace period.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin"
                ],
                "summary": "Rotate API key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "API key to rotate",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Grace period for old key",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_handler.rotateKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.rotateKeyResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request or grace period",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns service health status, build version, and dependency health (Redis, upstream).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "healthy",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.HealthResponse"
                        }
                    },
                    "503": {
                        "description": "degraded — one or more dependencies unhealthy",
                        "schema": {
                            "$ref": "#/definitions/internal_handler.HealthResponse"
                        }
                    }
                }
            }
        },
        "/openapi.json": {
            "get": {
                "description": "Returns the generated OpenAPI specification as JSON.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "OpenAPI spec",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/v1/drugs/autocomplete": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns drug names matching the given prefix. Fast typeahead endpoint for building search UIs.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drugs"
                ],
                "summary": "Drug name autocomplete",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Prefix to match (min 2 chars)",
                        "name": "q",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Max results (default: 10, max: 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "array",
                                "items": {
                                    "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.DrugNameEntry"
                                }
                            }
                        }
                    },
                    "400": {
                        "description": "Missing or invalid q parameter",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream service error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/drugs/class": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Looks up a drug by generic or brand name and returns its pharmacological classes, brand names, and generic name. Tries generic name first, falls back to brand name.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drugs"
                ],
                "summary": "Look up drug class by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Drug name (generic or brand, e.g. simvastatin, Zocor)",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.DrugClassResponse"
                        }
                    },
                    "400": {
                        "description": "Missing or empty name parameter",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Drug not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream service error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/drugs/classes": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns a paginated list of pharmacological drug classes from DailyMed. Defaults to EPC (Established Pharmacologic Class) type. Supports filtering by type: epc, moa, pe, cs, or all.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drugs"
                ],
                "summary": "List drug classes",
                "parameters": [
                    {
                        "enum": [
                            "epc",
                            "moa",
                            "pe",
                            "cs",
                            "all"
                        ],
                        "type": "string",
                        "description": "Filter by class type (default: epc)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Results per page (default: 50, max: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.PaginatedResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream service error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/drugs/classes/drugs": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns a paginated list of drugs belonging to a specific pharmacological class, resolved via FDA NDC data. Returns empty data (not 404) for unknown classes.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drugs"
                ],
                "summary": "List drugs in a class",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Pharmacological class name (e.g. HMG-CoA Reductase Inhibitor)",
                        "name": "class",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Results per page (default: 100, max: 500)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.PaginatedResponse"
                        }
                    },
                    "400": {
                        "description": "Missing or empty class parameter",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream service error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/drugs/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Look up a single drug by name or NDC and return SPL metadata plus parsed interaction sections. NDC is normalized and resolved to drug name internally.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spl"
                ],
                "summary": "Drug info card with interactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Drug name",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "NDC code (any format)",
                        "name": "ndc",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.DrugInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Missing name or ndc",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "NDC not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream service error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/drugs/interactions": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Submit 2-10 drug identifiers (name or NDC) and get cross-referenced interaction warnings from FDA SPL labels. Each drug's Section 7 is searched for mentions of the other drugs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spl"
                ],
                "summary": "Check drug interactions",
                "parameters": [
                    {
                        "description": "Drug identifiers to check",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.InteractionCheckRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.InteractionCheckResponse"
                        }
                    },
                    "400": {
                        "description": "Too few/many drugs or invalid input",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream service error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/drugs/names": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns a paginated list of drug names from the DailyMed dataset. Supports case-insensitive substring search and type filtering (generic/brand).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drugs"
                ],
                "summary": "List drug names",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search substring filter (case-insensitive)",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "generic",
                            "brand",
                            "all"
                        ],
                        "type": "string",
                        "description": "Filter by type: generic, brand, or all",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Results per page (default: 50, max: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.PaginatedResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream service error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/drugs/ndc/{ndc}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Accepts a product NDC (dash-separated), queries cash-drugs upstream, and returns drug name, generic name, and therapeutic classes. Supports 5-4, 4-4, and 5-3 formats with automatic fallback to padded 5-4.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "drugs"
                ],
                "summary": "Look up drug by NDC",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Product NDC with dash (e.g. 58151-158, 0069-3150, 00069-315)",
                        "name": "ndc",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.DrugDetailResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/drugs/rxnorm/profile": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Resolves a drug name via approximate match, then assembles NDCs, generic equivalents, and related concepts into a single response.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rxnorm"
                ],
                "summary": "Get unified drug profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Drug name (generic or brand)",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.RxNormProfile"
                        }
                    },
                    "400": {
                        "description": "Missing name parameter",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Drug not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream service error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/drugs/rxnorm/search": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Approximate match search via RxNorm. Returns up to 5 candidates ranked by score. Includes spelling suggestions when no matches are found.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rxnorm"
                ],
                "summary": "Search drugs by name (RxNorm)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Drug name to search for",
                        "name": "name",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.RxNormSearchResult"
                        }
                    },
                    "400": {
                        "description": "Missing name parameter",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No drugs found",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream service error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/drugs/rxnorm/{rxcui}/generics": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns generic product information for the given RxNorm concept identifier.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rxnorm"
                ],
                "summary": "Get generic products for an RxCUI",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RxNorm concept unique identifier",
                        "name": "rxcui",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.RxNormGenericResponse"
                        }
                    },
                    "404": {
                        "description": "RxCUI not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream service error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/drugs/rxnorm/{rxcui}/ndcs": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns NDC codes associated with the given RxNorm concept identifier.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rxnorm"
                ],
                "summary": "Get NDCs for an RxCUI",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RxNorm concept unique identifier",
                        "name": "rxcui",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.RxNormNDCResponse"
                        }
                    },
                    "404": {
                        "description": "RxCUI not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream service error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/drugs/rxnorm/{rxcui}/related": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Returns all related concepts grouped by type (ingredients, brand names, dose forms, clinical drugs, branded drugs).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rxnorm"
                ],
                "summary": "Get related concepts for an RxCUI",
                "parameters": [
                    {
                        "type": "string",
                        "description": "RxNorm concept unique identifier",
                        "name": "rxcui",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.RxNormRelatedResponse"
                        }
                    },
                    "404": {
                        "description": "RxCUI not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream service error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/drugs/spls": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Search Structured Product Labels by drug name. Returns paginated SPL metadata from DailyMed.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spl"
                ],
                "summary": "Search SPL documents",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Drug name to search",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Results per page (default: 20, max: 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.PaginatedResponse"
                        }
                    },
                    "400": {
                        "description": "Missing name parameter",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream service error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/drugs/spls/{setid}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Retrieve SPL metadata and parsed Drug Interactions (Section 7) from the SPL XML document.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "spl"
                ],
                "summary": "Get SPL detail with interactions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SPL set ID (UUID format)",
                        "name": "setid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.SPLDetail"
                        }
                    },
                    "404": {
                        "description": "SPL not found",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    },
                    "502": {
                        "description": "Upstream service error",
                        "schema": {
                            "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Returns build version, git commit, git branch, and Go runtime version.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "public"
                ],
                "summary": "Build version info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_finish06_drug-gate_internal_apikey.APIKey": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "app_name": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "origins": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rate_limit": {
                    "type": "integer"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.DrugCheckResult": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "has_interactions": {
                    "type": "boolean"
                },
                "input_name": {
                    "type": "string"
                },
                "input_type": {
                    "type": "string"
                },
                "resolved_name": {
                    "type": "string"
                },
                "spl_setid": {
                    "type": "string"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.DrugClass": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.DrugClassResponse": {
            "type": "object",
            "properties": {
                "brand_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "classes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.DrugClass"
                    }
                },
                "generic_name": {
                    "type": "string"
                },
                "query_name": {
                    "type": "string"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.DrugDetailResponse": {
            "type": "object",
            "properties": {
                "classes": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "generic_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "ndc": {
                    "type": "string"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.DrugIdentifier": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "ndc": {
                    "type": "string"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.DrugInfoResponse": {
            "type": "object",
            "properties": {
                "adverse_reactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.InteractionSection"
                    }
                },
                "contraindications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.InteractionSection"
                    }
                },
                "drug_name": {
                    "type": "string"
                },
                "input_type": {
                    "type": "string"
                },
                "input_value": {
                    "type": "string"
                },
                "interactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.InteractionSection"
                    }
                },
                "spl": {
                    "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.SPLSource"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.InteractionSection"
                    }
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.DrugNameEntry": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.InteractionCheckRequest": {
            "type": "object",
            "properties": {
                "drugs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.DrugIdentifier"
                    }
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.InteractionCheckResponse": {
            "type": "object",
            "properties": {
                "checked_pairs": {
                    "type": "integer"
                },
                "drugs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.DrugCheckResult"
                    }
                },
                "found_interactions": {
                    "type": "integer"
                },
                "interactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.InteractionMatch"
                    }
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.InteractionMatch": {
            "type": "object",
            "properties": {
                "drug_a": {
                    "type": "string"
                },
                "drug_b": {
                    "type": "string"
                },
                "section_title": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "spl_setid": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.InteractionSection": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.PaginatedResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "pagination": {
                    "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.Pagination"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                },
                "total_pages": {
                    "type": "integer"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.RxNormCandidate": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "rxcui": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.RxNormConcept": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "rxcui": {
                    "type": "string"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.RxNormGenericResponse": {
            "type": "object",
            "properties": {
                "generics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.RxNormConcept"
                    }
                },
                "rxcui": {
                    "type": "string"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.RxNormNDCResponse": {
            "type": "object",
            "properties": {
                "ndcs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rxcui": {
                    "type": "string"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.RxNormProfile": {
            "type": "object",
            "properties": {
                "brand_names": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "generic": {
                    "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.RxNormConcept"
                },
                "name": {
                    "type": "string"
                },
                "ndcs": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "query": {
                    "type": "string"
                },
                "related": {
                    "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.RxNormRelatedResponse"
                },
                "rxcui": {
                    "type": "string"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.RxNormRelatedResponse": {
            "type": "object",
            "properties": {
                "brand_names": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.RxNormConcept"
                    }
                },
                "branded_drugs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.RxNormConcept"
                    }
                },
                "clinical_drugs": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.RxNormConcept"
                    }
                },
                "dose_forms": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.RxNormConcept"
                    }
                },
                "ingredients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.RxNormConcept"
                    }
                },
                "rxcui": {
                    "type": "string"
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.RxNormSearchResult": {
            "type": "object",
            "properties": {
                "candidates": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.RxNormCandidate"
                    }
                },
                "query": {
                    "type": "string"
                },
                "suggestions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.SPLDetail": {
            "type": "object",
            "properties": {
                "adverse_reactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.InteractionSection"
                    }
                },
                "contraindications": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.InteractionSection"
                    }
                },
                "interactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.InteractionSection"
                    }
                },
                "published_date": {
                    "type": "string"
                },
                "setid": {
                    "type": "string"
                },
                "spl_version": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_finish06_drug-gate_internal_model.InteractionSection"
                    }
                }
            }
        },
        "github_com_finish06_drug-gate_internal_model.SPLSource": {
            "type": "object",
            "properties": {
                "published_date": {
                    "type": "string"
                },
                "setid": {
                    "type": "string"
                },
                "spl_version": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "internal_handler.HealthResponse": {
            "type": "object",
            "properties": {
                "dependencies": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "status": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "internal_handler.cacheClearResult": {
            "type": "object",
            "properties": {
                "keys_deleted": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "internal_handler.createKeyRequest": {
            "type": "object",
            "properties": {
                "app_name": {
                    "type": "string"
                },
                "origins": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rate_limit": {
                    "type": "integer"
                }
            }
        },
        "internal_handler.rotateKeyRequest": {
            "type": "object",
            "properties": {
                "grace_period": {
                    "type": "string"
                }
            }
        },
        "internal_handler.rotateKeyResponse": {
            "type": "object",
            "properties": {
                "new_key": {
                    "type": "string"
                },
                "old_key": {
                    "type": "string"
                },
                "old_key_expires_at": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "AdminAuth": {
            "description": "Bearer token for admin endpoints. Value: \"Bearer {ADMIN_SECRET}\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "ApiKeyAuth": {
            "description": "Publishable API key for accessing /v1/* endpoints. Create one via POST /admin/keys.",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "drug-gate API",
	Description:      "Drug information gateway — NDC lookup, therapeutic classes, and more.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
